DROP TABLE IF EXISTS dog;
DROP TABLE IF EXISTS user;

CREATE TABLE user (
    user_id INTEGER NOT NULL,
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    password TEXT NOT NULL
);


CREATE TABLE dog (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    breed TEXT NOT NULL,
    photo_path TEXT NOT NULL,
    username TEXT UNIQUE NOT NULL,
    user_id INTEGER NOT NULL, 
    FOREIGN KEY (user_id) REFERENCES user (id),
    discovered TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
